title: vcMedBots
description: Patient Engagement Chatbots
footer_company_name: Vcrsoft LLC
baseurl: ""
url: "https://vcrsoft.com"
markdown: kramdown
permalink: /resources/:title/

collections:
  resources:
    output: true
    permalink: /resources/:title/

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-sitemap
