# Site settings
title: VCRSOFT LLC
description: Patient Engagement Chatbots - A friendly conversational interface enabling patients to register, book appointments, view medical records, or message their doctor
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vcrsoft.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Navigation
header_pages:
  - about.md
  - blog.md

# Author settings
author:
  name: VCRSOFT LLC
  email: your-email@domain.com
