title: vcMedBots
description: Patient Engagement Chatbots
baseurl: ""
url: "https://vcrsoft.github.io"
markdown: kramdown

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
