# Site settings
title: VCRSOFT LLC
description: >
  Patient Engagement Chatbots - A friendly conversational interface enabling patients to register, book appointments, view medical records, or message their doctor.
author: VCRSOFT LLC
baseurl: "/docs" # Required if the source directory is a subfolder
url: "https://www.vcrsoft.com" # Update with your custom domain

# Jekyll theme
theme: minima # A simple, supported theme by GitHub Pages

# Plugins
plugins:
  - jekyll-seo-tag # Improves SEO for your site
  - jekyll-sitemap # Generates a sitemap for search engines
  - jekyll-feed # Generates an RSS feed for your blog

# Markdown options
markdown: kramdown
highlighter: rouge

# Exclude files from Jekyll processing
exclude:
  - README.md
  - index.html

# Additional settings
paginate: 5 # Number of posts per page (if you add a blog later)
